# Generated by Django 5.1.4 on 2024-12-30 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_auth_credential',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_fname',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_lname',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_phoneNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='employee_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
