# Generated by Django 5.1.4 on 2024-12-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userinfo_user_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userinfo'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='employee_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userinfo'),
        ),
    ]
