# Generated by Django 5.1.4 on 2025-01-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_company_company_total_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
