# Generated by Django 5.1.4 on 2025-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_userinfo_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_role',
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='employee_role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
